# Generated by Django 2.1.2 on 2018-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('proprietor', models.CharField(max_length=64)),
                ('license_no', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('pincode', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('Phone_no', models.IntegerField()),
                ('image', models.FileField(upload_to='photos/acceptor')),
            ],
        ),
        migrations.CreateModel(
            name='assigned_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_assigned_time', models.DateTimeField(auto_now=True)),
                ('vehicle_return_time', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('pinCode', models.IntegerField()),
                ('Phone_no', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('UID', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('Driving_License', models.CharField(max_length=32)),
                ('Driving_License_image', models.FileField(upload_to='photos/collector/DL')),
                ('image', models.FileField(upload_to='photos/collector')),
            ],
        ),
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('pinCode', models.IntegerField()),
                ('Phone_no', models.IntegerField()),
                ('BirthDate', models.DateField()),
                ('UID', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password1', models.CharField(max_length=16)),
                ('password2', models.CharField(max_length=16)),
                ('image', models.FileField(upload_to='photos/doner')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('RC_no', models.CharField(max_length=32)),
                ('registration_no', models.CharField(max_length=16)),
                ('last_servicing', models.DateField()),
                ('fuel_type', models.CharField(max_length=32)),
                ('insurence_no', models.CharField(max_length=32)),
                ('owner_name', models.CharField(max_length=32)),
                ('Date_purchase', models.DateField()),
                ('owner_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='collector_id',
            field=models.ManyToManyField(blank=True, to='Medical_Donation.Collector'),
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='destination',
            field=models.ManyToManyField(blank=True, to='Medical_Donation.Doner'),
        ),
        migrations.AddField(
            model_name='assigned_vehicle',
            name='vehicle_id',
            field=models.ManyToManyField(blank=True, to='Medical_Donation.vehicle'),
        ),
    ]
